# Default configuration for Hybrid HRM+EBM Agent
app:
  name: hybrid_hrm_ebm_agent
  env: development

logging:
  level: INFO
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"

# Example knobs used by decoding / scoring
inference:
  max_new_tokens: 256
  temperature: 0.2
  top_p: 0.95
  length_penalty: 0.0

energy_model:
  lambda_weight: 1.0
  calibration: none

# Placeholder for future datasets/eval configs
swe_bench:
  enabled: false
