app:
  name: hybrid_hrm_ebm_agent
  version: 0.1.0

runtime:
  seed: 42
  device: cpu
  log_level: INFO

llm:
  backend: tiny
  model_name: TinyCausalLM
  max_new_tokens: 128
  temperature: 0.2
  top_k: 8

hrm:
  plan_update_interval: 4
  risk_threshold: 0.35

ebm:
  rerank_k: 4
  shape_weight: 0.7
  length_penalty: 0.01

decoding:
  strategy: topk_then_rerank
  json_cfg_enabled: false

memory:
  enabled: false

