name: CI

on:
  push:
    branches: [ master, main, pr1-devex-ci ]
  pull_request:
    branches: [ master, main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install pytest ruff mypy

      - name: Ruff Lint
        run: ruff check .

      - name: Mypy Type Check
        run: mypy hybrid_agent || true

      - name: Pytest
        run: pytest -q
